<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <OutputType>Library</OutputType>  
    <Nullable>enable</Nullable>
	<AssemblyName>ProcessFileOnQueue</AssemblyName>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Amazon.Lambda.Core" Version="2.7.1" />
    <PackageReference Include="Amazon.Lambda.Serialization.SystemTextJson" Version="2.4.4" />
    <PackageReference Include="Amazon.Lambda.SQSEvents" Version="2.2.0" />
    <PackageReference Include="AWSSDK.DynamoDBv2" Version="4.0.6.5" />
    <PackageReference Include="AWSSDK.S3" Version="4.0.7.7" />
    <PackageReference Include="AWSSDK.SecretsManager" Version="4.0.1.6" />
    <PackageReference Include="AWSSDK.SQS" Version="4.0.1.8" />
    <PackageReference Include="Microsoft.Extensions.Configuration" Version="9.0.9" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\..\Amazon-SP-API\Source\FikaAmazonAPI\FikaAmazonAPI.csproj" />
  </ItemGroup>

</Project>
